# Generated by Django 6.0.7 on 2026-09-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_release_date_movie_genre_movie_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text='Разрешённая ссылка на видео', null=True),
        ),
    ]
